// POKEDEX
// Aqui esta la informacion de todos los pokemon disponibles para el juego
// En total son 151

class pokemon {
    constructor(id, nombre, tipo1, tipo2, imagen){
        this.id = id
        this.nombre = nombre
        this.tipo1 = tipo1
        this.tipo2 = tipo2
        this.imagen = imagen
    
    }
}

const listaPokemon = [
    new pokemon (1, 'bulbasaur', 'planta','veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png'),
    new pokemon (2, 'ivysaur','planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png'),
    new pokemon (3, 'venusaur', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png'),
    new pokemon (4, 'charmander', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png'),
    new pokemon (5, 'charmeleon', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png'),
    new pokemon (6, 'charizard', 'fuego', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png'),
    new pokemon (7, 'squirtle', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png'),
    new pokemon (8, 'wartortle', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png'),
    new pokemon (9, 'blastoise', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png'),
    new pokemon (10, 'caterpie', 'bicho', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png'),
    new pokemon (11, 'metapod', 'bicho', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png'),
    new pokemon (12, 'butterfree', 'bicho', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png'),
    new pokemon (13, 'weedle', 'bicho', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png'),
    new pokemon (14, 'kakuna', 'bicho', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png'),
    new pokemon (15, 'beedrill', 'bicho', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png'),
    new pokemon (16, 'pidgey', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png'),
    new pokemon (17, 'pidgeotto', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png'),
    new pokemon (18, 'pidgeot', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png'),
    new pokemon (19, 'rattata', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png'),
    new pokemon (20, 'raticate', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png'),
    new pokemon (21, 'spearow', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png'),
    new pokemon (22, 'fearow', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/022.png'),
    new pokemon (23, 'ekans', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png'),
    new pokemon (24, 'arbok', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/024.png'),
    new pokemon (25, 'pikachu', 'electrico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png'),
    new pokemon (26, 'raichu', 'electrico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/026.png'),
    new pokemon (27, 'sandshrew', 'tierra', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png'),
    new pokemon (28, 'sandslash', 'tierra', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/028.png'),
    new pokemon (29, 'nidoranf', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/029.png'),
    new pokemon (30, 'nidorina', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/030.png'),
    new pokemon (31, 'nidoqueen', 'veneno', 'tierra', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/031.png'),
    new pokemon (32, 'nidoranh', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/032.png'),
    new pokemon (33, 'nidorino', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/033.png'),
    new pokemon (34, 'nidoking', 'veneno', 'tierra', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/034.png'),
    new pokemon (35, 'clefairy', 'hada', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png'),
    new pokemon (36, 'clefable', 'hada', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/036.png'),
    new pokemon (37, 'vulpix', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png'),
    new pokemon (38, 'ninetails', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/038.png'),
    new pokemon (39, 'jigglypuff', 'normal', 'hada', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/039.png'),
    new pokemon (40, 'wigglytuff', 'normal', 'hada', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/040.png'),
    new pokemon (41, 'zubat', 'veneno', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/041.png'),
    new pokemon (42, 'golbat', 'veneno', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/042.png'),
    new pokemon (43, 'oddish', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/043.png'),
    new pokemon (44, 'gloom', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/044.png'),
    new pokemon (45, 'vileplume', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/045.png'),
    new pokemon (46, 'paras', 'bicho', 'planta', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/046.png'),
    new pokemon (47, 'parasect', 'bicho', 'planta', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/047.png'),
    new pokemon (48, 'venonat', 'bicho', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/048.png'),
    new pokemon (49, 'venomoth', 'bicho', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/049.png'),
    new pokemon (50, 'diglett', 'tierra', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/050.png'),
    new pokemon (51, 'dugtrio', 'tierra', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/051.png'),
    new pokemon (52, 'meowth', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/052.png'),
    new pokemon (53, 'persian', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/053.png'),
    new pokemon (54, 'psyduck', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/054.png'),
    new pokemon (55, 'golduck', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/055.png'),
    new pokemon (56, 'mankey', 'pelea', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/056.png'),
    new pokemon (57, 'primeape', 'pelea', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/057.png'),
    new pokemon (58, 'growlithe', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/058.png'),
    new pokemon (59, 'arcanine', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/059.png'),
    new pokemon (60, 'poliwag', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/060.png'),
    new pokemon (61, 'poliwhirl', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/061.png'),
    new pokemon (62, 'poliwrath', 'agua', 'lucha', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/062.png'),
    new pokemon (63, 'abra', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/063.png'),
    new pokemon (64, 'kadabra', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/064.png'),
    new pokemon (65, 'alakazam', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/065.png'),
    new pokemon (66, 'machop', 'lucha', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/066.png'),
    new pokemon (67, 'machoke', 'lucha', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/067.png'),
    new pokemon (68, 'machamp', 'lucha', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/068.png'),
    new pokemon (69, 'bellsprout', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/069.png'),
    new pokemon (70, 'weepinbell', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/070.png'),
    new pokemon (71, 'victreebell', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/071.png'),
    new pokemon (72, 'tentacool', 'agua', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/072.png'),
    new pokemon (73, 'tentacruel', 'agua', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/073.png'),
    new pokemon (74, 'geodude', 'roca', 'tierra', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/074.png'),
    new pokemon (75, 'graveler', 'roca', 'tierra', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/075.png'),
    new pokemon (76, 'golem', 'roca', 'tierra', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/076.png'),
    new pokemon (77, 'ponyta', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/077.png'),
    new pokemon (78, 'rapidash', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/078.png'),
    new pokemon (79, 'slowpoke', 'agua', 'psiquico', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/079.png'),
    new pokemon (80, 'slowbro', 'agua', 'psiquico', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/080.png'),
    new pokemon (81, 'magnemite', 'electrico', 'acero', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/081.png'),
    new pokemon (82, 'magneton', 'electrico', 'acero', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/082.png'),
    new pokemon (83, 'farfetchd', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/083.png'),
    new pokemon (84, 'doduo', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/084.png'),
    new pokemon (85, 'dodrio', 'normal', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/085.png'),
    new pokemon (86, 'seel', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/086.png'),
    new pokemon (87, 'dewong', 'agua', 'hielo', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/087.png'),
    new pokemon (88, 'grimer', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/088.png'),
    new pokemon (89, 'muk', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/089.png'),
    new pokemon (90, 'shellder', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/090.png'),
    new pokemon (91, 'cloyster', 'agua', 'hielo', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/091.png'),
    new pokemon (92, 'gastly', 'fantasma', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/092.png'),
    new pokemon (93, 'haunter', 'fantasma', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/093.png'),
    new pokemon (94, 'gengar', 'fantasma', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/094.png'),
    new pokemon (95, 'onix', 'roca', 'tierra', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/095.png'),
    new pokemon (96, 'drowzee', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/096.png'),
    new pokemon (97, 'hypno', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/097.png'),
    new pokemon (98, 'krabby', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/098.png'),
    new pokemon (99, 'kingler', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/099.png'),
    new pokemon (100, 'voltorb', 'electrico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/100.png'),
    new pokemon (101, 'electrode', 'electrico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/101.png'),
    new pokemon (102, 'exeggcute', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/102.png'),
    new pokemon (103, 'exeggutor', 'planta', 'veneno', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/103.png'),
    new pokemon (104, 'cubone', 'tierra', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/104.png'),
    new pokemon (105, 'marowak', 'tierra', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/105.png'),
    new pokemon (106, 'hitmonlee', 'pelea', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/106.png'),
    new pokemon (107, 'hitmonchan', 'pelea', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/107.png'),
    new pokemon (108, 'lickitung', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/108.png'),
    new pokemon (109, 'koffing', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/109.png'),
    new pokemon (110, 'weezing', 'veneno', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/110.png'),
    new pokemon (111, 'rhyhorn', 'tierra', 'roca', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/111.png'),
    new pokemon (112, 'rhydon', 'tierra', 'roca', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/112.png'),
    new pokemon (113, 'chansey', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/113.png'),
    new pokemon (114, 'tangela', 'planta', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/114.png'),
    new pokemon (115, 'kangaskhan', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/115.png'),
    new pokemon (116, 'horsea', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/116.png'),
    new pokemon (117, 'seadra', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/117.png'),
    new pokemon (118, 'goldeen', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/118.png'),
    new pokemon (119, 'seaking', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/119.png'),
    new pokemon (120, 'staryu', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/120.png'),
    new pokemon (121, 'starmie', 'agua', 'psiquico', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/121.png'),
    new pokemon (122, 'mr mime', 'psiquico', 'hada', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/122.png'),
    new pokemon (123, 'scyther', 'bicho', 'acero', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/123.png'),
    new pokemon (124, 'jynx', 'hielo', 'psiquico', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/124.png'),
    new pokemon (125, 'electabuzz', 'electrico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/125.png'),
    new pokemon (126, 'magmar', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/126.png'),
    new pokemon (127, 'pinsir', 'bicho', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/127.png'),
    new pokemon (128, 'tauros', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/128.png'),
    new pokemon (129, 'magikarp', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/129.png'),
    new pokemon (130, 'gyarados', 'agua', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/130.png'),
    new pokemon (131, 'lapras', 'agua', 'hielo', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/131.png'),
    new pokemon (132, 'ditto', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/132.png'),
    new pokemon (133, 'eevee', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/133.png'),
    new pokemon (134, 'vaporeon', 'agua', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/134.png'),
    new pokemon (135, 'jolteon', 'electrico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/135.png'),
    new pokemon (136, 'flareon', 'fuego', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/136.png'),
    new pokemon (137, 'porygon', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/137.png'),
    new pokemon (138, 'omanyte', 'roca', 'agua', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/138.png'),
    new pokemon (139, 'omaster', 'roca', 'agua', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/139.png'),
    new pokemon (140, 'kabuto', 'roca', 'agua', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/140.png'),
    new pokemon (141, 'kabutops', 'roca', 'agua', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/141.png'),
    new pokemon (142, 'aerodactyl', 'roca', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/142.png'),
    new pokemon (143, 'snorlax', 'normal', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/143.png'),
    new pokemon (144, 'articuno', 'hielo', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/144.png'),
    new pokemon (145, 'zapdos', 'electrico', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/145.png'),
    new pokemon (146, 'moltres', 'fuego', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/146.png'),
    new pokemon (147, 'dratini', 'dragon', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/147.png'),
    new pokemon (148, 'dragonair', 'dragon', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/148.png'),
    new pokemon (149, 'dragonite', 'dragon', 'volador', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/149.png'),
    new pokemon (150, 'mewtwo', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/150.png'),
    new pokemon (151, 'mew', 'psiquico', 'none', 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/151.png'),
    
];